print("Program starting.")
brand = input("Insert car brand: ")
model = input("Insert car model: ")
print(f"Car brand is \"{brand}\" ",end="")
print("the model is ", f"{model}'", sep="'")
print("Program ending.")